# Generated by Django 6.0.2 on 2026-08-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema_relatado', models.TextField(blank=True, help_text='Dores, limitações, preferências...')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('grupo_muscular', models.CharField(blank=True, max_length=100)),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20)),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticoes', models.PositiveIntegerField(default=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
