# Generated by Django 6.0.2 on 2026-08-16 21:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichaExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticoes', models.PositiveIntegerField(default=12)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treino.exercicio')),
            ],
            options={
                'ordering': ('ordem',),
            },
        ),
        migrations.CreateModel(
            name='FichaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Minha ficha', max_length=150)),
                ('objetivo', models.CharField(blank=True, max_length=150)),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('exercicios', models.ManyToManyField(related_name='fichas', through='treino.FichaExercicio', to='treino.exercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fichaexercicio',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treino.fichatreino'),
        ),
        migrations.CreateModel(
            name='SolicitacaoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='kg', max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, help_text='metros, ex: 1.75', max_digits=4)),
                ('idade', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=20)),
                ('percentual_gordura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('nivel_experiencia', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20)),
                ('objetivo_principal', models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('emagrecimento', 'Emagrecimento'), ('forca', 'Força'), ('resistencia', 'Resistência'), ('saude_geral', 'Saúde geral')], max_length=20)),
                ('frequencia_semanal', models.PositiveSmallIntegerField(help_text='Dias por semana', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('tempo_por_sessao', models.PositiveIntegerField(help_text='Minutos disponíveis por sessão')),
                ('lesoes_dores', models.TextField(blank=True, help_text='Dores, limitações, lesões crônicas...')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ficha_gerada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_origem', to='treino.fichatreino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
