# Generated by Django 6.0.7 on 2026-08-19 03:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatreino',
            name='exercicios',
        ),
        migrations.RemoveField(
            model_name='fichatreino',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='solicitacaotreino',
            name='ficha_gerada',
        ),
        migrations.RemoveField(
            model_name='solicitacaotreino',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='exercicio',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='video_url',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='grupo_muscular',
            field=models.CharField(choices=[('peito', 'Peito'), ('costas', 'Costas'), ('pernas', 'Pernas'), ('ombro', 'Ombro'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('abdomen', 'Abdômen'), ('gluteos', 'Glúteos'), ('cardio', 'Cardio'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='exercicios/'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='link_youtube',
            field=models.URLField(default='', help_text='Link do vídeo de referência no YouTube'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PerfilTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, help_text='Altura em metros. Ex: 1.75', max_digits=4)),
                ('idade', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('percentual_gordura', models.DecimalField(blank=True, decimal_places=1, help_text='Percentual de gordura corporal, se souber', max_digits=4, null=True)),
                ('nivel_experiencia', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=20)),
                ('objetivo', models.CharField(choices=[('emagrecer', 'Emagrecer'), ('ganhar_massa', 'Ganhar massa muscular'), ('manter', 'Manter o condicionamento'), ('definicao', 'Definição muscular')], max_length=20)),
                ('problemas_saude', models.TextField(blank=True, help_text='Problemas de saúde relevantes')),
                ('frequencia_semanal', models.PositiveSmallIntegerField(help_text='Quantos dias por semana pretende treinar', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('tempo_por_sessao', models.PositiveSmallIntegerField(help_text='Tempo disponível por treino, em minutos')),
                ('lesoes_dores', models.TextField(blank=True, help_text='Lesões ou dores atuais')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_treino', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TreinoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_texto', models.TextField(help_text='Resposta bruta da IA, em texto')),
                ('conteudo_json', models.JSONField(blank=True, help_text='Resposta estruturada (dias/exercícios), se disponível', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos_gerados', to='treino.perfiltreino')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='FichaExercicio',
        ),
        migrations.DeleteModel(
            name='FichaTreino',
        ),
        migrations.DeleteModel(
            name='SolicitacaoTreino',
        ),
    ]
