# Generated by Django 6.0.2 on 2026-08-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel_atividade',
            field=models.CharField(blank=True, choices=[('sedentario', 'Sedentário (pouco ou nenhum exercício)'), ('leve', 'Levemente ativo (exercício leve, 1 a 3x por semana)'), ('moderado', 'Moderadamente ativo (exercício moderado, 3 a 5x por semana)'), ('intenso', 'Altamente ativo (exercício intenso, 6 a 7x por semana)'), ('muito_intenso', 'Extremamente ativo (exercício muito intenso ou trabalho físico)')], max_length=20, null=True, verbose_name='nível de atividade física'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('emagrecimento', 'Emagrecimento'), ('hipertrofia', 'Hipertrofia (ganho de massa muscular)'), ('manutencao', 'Manutenção do peso')], max_length=20, null=True, verbose_name='objetivo'),
        ),
    ]
