# Generated by Django 6.0.7 on 2026-08-14 21:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peso em kg')),
                ('agua', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='água consumida em litros')),
                ('tempo_cardio', models.PositiveIntegerField(default=0, verbose_name='tempo de cardio em minutos')),
                ('seguiu_dieta', models.BooleanField(default=False, verbose_name='seguiu a dieta')),
                ('realizou_treino', models.BooleanField(default=False, verbose_name='realizou o treino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'data'), name='monitoramento_unico_por_dia')],
            },
        ),
    ]
