# Generated by Django 6.0.2 on 2026-08-16 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Meu plano alimentar', max_length=150, verbose_name='nome do plano')),
                ('calorias_meta', models.PositiveIntegerField(blank=True, null=True, verbose_name='meta de calorias (kcal)')),
                ('proteina_meta', models.PositiveIntegerField(blank=True, null=True, verbose_name='meta de proteína (g)')),
                ('carboidrato_meta', models.PositiveIntegerField(blank=True, null=True, verbose_name='meta de carboidrato (g)')),
                ('gordura_meta', models.PositiveIntegerField(blank=True, null=True, verbose_name='meta de gordura (g)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_alimentares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cafe', 'Café da manhã'), ('almoco', 'Almoço'), ('lanche', 'Lanche da tarde'), ('jantar', 'Jantar')], max_length=10, verbose_name='refeição')),
                ('descricao', models.TextField(help_text='Ex: Ovos mexidos, aveia, banana', verbose_name='o que comer')),
                ('calorias', models.PositiveIntegerField(default=0, verbose_name='calorias (kcal)')),
                ('proteina', models.PositiveIntegerField(default=0, verbose_name='proteína (g)')),
                ('carboidrato', models.PositiveIntegerField(default=0, verbose_name='carboidrato (g)')),
                ('gordura', models.PositiveIntegerField(default=0, verbose_name='gordura (g)')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='dieta.planoalimentar')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
    ]
