# Generated by Django 6.0.7 on 2026-08-19 18:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicao',
            name='plano',
        ),
        migrations.CreateModel(
            name='PerfilDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, help_text='Altura em metros. Ex: 1.75', max_digits=4)),
                ('idade', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('nivel_atividade', models.CharField(choices=[('sedentario', 'Sedentário (pouco ou nenhum exercício)'), ('leve', 'Leve (exercício leve 1 a 3x/semana)'), ('moderado', 'Moderado (exercício moderado 3 a 5x/semana)'), ('intenso', 'Intenso (exercício pesado 6 a 7x/semana)'), ('muito_intenso', 'Muito intenso (exercício pesado + trabalho físico)')], max_length=20)),
                ('objetivo', models.CharField(choices=[('emagrecer', 'Emagrecer'), ('manter', 'Manter o peso'), ('ganhar_massa', 'Ganhar massa muscular')], max_length=20)),
                ('restricao_alimentar', models.CharField(choices=[('nenhuma', 'Nenhuma'), ('vegetariano', 'Vegetariano'), ('vegano', 'Vegano'), ('sem_gluten', 'Sem glúten'), ('sem_lactose', 'Sem lactose'), ('low_carb', 'Low carb'), ('outra', 'Outra (descrever abaixo)')], default='nenhuma', max_length=20)),
                ('restricao_outra_descricao', models.CharField(blank=True, help_text='Preencha se escolheu "Outra" acima', max_length=200)),
                ('alergias', models.TextField(blank=True, help_text='Ex: amendoim, frutos do mar, lactose. Deixe em branco se não tiver.')),
                ('alimentos_que_nao_gosta', models.TextField(blank=True, help_text='Alimentos que prefere evitar, mesmo sem ser alergia')),
                ('condicoes_saude', models.TextField(blank=True, help_text='Ex: diabetes, hipertensão, colesterol alto')),
                ('orcamento_semanal', models.DecimalField(decimal_places=2, help_text='Quanto pode gastar com alimentação por semana, em R$', max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('refeicoes_por_dia', models.PositiveSmallIntegerField(default=4, help_text='Quantas refeições prefere fazer por dia', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_dieta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DietaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias_alvo', models.PositiveIntegerField(help_text='Meta diária de calorias (kcal)')),
                ('proteina_g', models.PositiveIntegerField(help_text='Meta diária de proteína (g)')),
                ('carboidrato_g', models.PositiveIntegerField(help_text='Meta diária de carboidrato (g)')),
                ('gordura_g', models.PositiveIntegerField(help_text='Meta diária de gordura (g)')),
                ('conteudo_texto', models.TextField(help_text='Resposta bruta da IA, em texto')),
                ('conteudo_json', models.JSONField(blank=True, help_text='Resposta estruturada, se disponível', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas_geradas', to='dieta.perfildieta')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='PlanoAlimentar',
        ),
        migrations.DeleteModel(
            name='Refeicao',
        ),
    ]
